#https://docs.drone.io/pipeline/docker/syntax/trigger/

#drone.yml
kind: pipeline
type: exec
name: default

# platform:
#   os: linux
#   arch: amd64

trigger:
  branch:
    - main
    - master
    - feature/*
  event:
    - push
    - pull_request
    - tag

steps:
- name: build
  commands:
  - docker build -t demo . --no-cache
  - echo "image running"
  - docker run -p 8088:8088 -d demo
  - echo "run success"