#https://docs.drone.io/pipeline/docker/syntax/trigger/
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
    - master
    - feature/*
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback

steps:
- name: backend
  image: golang:1.13-alpine
  environment:
    USERNAME:
      from_secret: username
  commands:
  - go clean -modcache
  - go mod tidy
  - go run .
  - echo TEST > /tmp/a.txt
  - cat /tmp/a.txt
  - echo "Contents of a.txt:" >> /drone/src/.drone_output
  - cat /tmp/a.txt >> /drone/src/.drone_output