#https://docs.drone.io/pipeline/docker/syntax/trigger/
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
    - master
    - feature/*
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback

steps:
- name: backend
  image: golang:1.20-alpine
  environment:
    USERNAME:
      from_secret: username
  ports:
  - "8888:8888"  # Map container's 8888 port to host's 8888 port
  commands:
  - go mod tidy
  - env GOOS=linux GOARCH=arm64 go build -o cmd
  - ./cmd
  # - echo TEST > /tmp/a.txt
  # - cat /tmp/a.txt
  # - tail -f /dev/null
  volumes:
  - name: data-volume
    path: /tmp  # Mount /tmp directory inside the container
