#https://docs.drone.io/pipeline/docker/syntax/trigger/

kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
    - master
    - feature/*
  event:
    - push
    - pull_request
    - tag

steps:
  - name: docker-build
    image: docker:dind
    volumes:
      - name: docker-sock
        path: /var/run/docker.sock
    commands:
      - docker ps
      - docker build -t demo . --no-cache
      - docker run -p 8088:8088 --name go-server -d demo
volumes:
  - name: docker-sock
    host:
      path: /var/run/docker.sock
