#https://docs.drone.io/pipeline/docker/syntax/trigger/
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
    - master
    - feature/*
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback

steps:
- name: backend
  image: golang:1.13-alpine
  environment:
    USERNAME:
      from_secret: username
  commands:
  - go build
  - go run .
  - echo TEST > a.txt
  - cat a.txt
