#https://docs.drone.io/pipeline/docker/syntax/trigger/

#drone.yml
kind: pipeline
type: exec
name: default

trigger:
  branch:
    - main
    - master
    - feature/*
  event:
    - push
    - pull_request
    - tag

steps:
  - name: build
    commands:
      - ./build.bat