#https://docs.drone.io/pipeline/docker/syntax/trigger/
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
    - master
    - feature/*
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback

steps:
- name: backend
  image: golang:1.20-alpine
  environment:
    USERNAME:
      from_secret: username
  commands:
  - go mod tidy
  - env GOOS=linux GOARCH=arm64 go build -o cmd
  - ./cmd
  volumes:
  - name: data-volume
    path: /tmp  # Mount /tmp directory inside the container

volumes:
- name: data-volume
  host:
    path: ./data  # Mount /data directory from the host machine