kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - main
    - master
    - feature/*
  event:
    - push
    - pull_request
    - tag

steps:
  - name: build
    image: golang:1.20-alpine
    pull: true
    commands:
      - go build -o myapp
      - cp myapp /workspace/myapp

  - name: create-docker-image
    image: docker:20
    pull: true
    settings:
      dockerfile: |
        FROM alpine:latest
        COPY myapp /usr/local/bin/myapp
        CMD ["myapp"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  - name: run
    image: alpine:latest
    commands:
      - /usr/local/bin/myapp
