#https://docs.drone.io/pipeline/docker/syntax/trigger/

#drone.yml
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
    - master
    - feature/*
  event:
    - push
    - pull_request
    - tag

steps:
- name: Start Docker Compose
  image: docker/compose:1.29.2  # 使用Docker Compose的合适版本
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  commands:
    - docker-compose -f docker-compose.yml up -d 