#https://docs.drone.io/pipeline/docker/syntax/trigger/
kind: pipeline
type: docker
name: default

trigger:
  branch:
    - main
    - master
    - feature/*
  event:
    - cron
    - custom
    - push
    - pull_request
    - tag
    - promote
    - rollback

steps:
- name: backend
  image: golang:1.20-alpine
  commands:
  - go mod tidy
  - env GOOS=linux GOARCH=arm64 go build -o cmd
  # - echo TEST > /tmp/a.txt
  # - cat /tmp/a.txt
  # - tail -f /dev/null

services:
  - name: golang-server
    image: golang:1.20-alpine
    command: ["./cmd"]
    volumes:
      - name: data-volume
        path: /tmp